<?php

use Drupal\Component\Datetime\DateTimePlus;

function weather_cron() {
  /*
    documentation
    https://zentracloud.com/api/v4/documentation/

    example GET request
     /v3/get_env_model_data
     /v3/get_readings
    */

  $server = "https://zentracloud.com/api/v3/get_readings/?";
  $token = "Token 877a8a6c16db4b3755693367eaa69e93267c07f0";

  // API calls have a limit of 1 per 60 seconds
  date_default_timezone_set('America/New_York');
  $end_date = date('Y-m-d H:i:s');
  // get 1 hour back for the start
  $interval = 3600;
  $start_date = date('Y-m-d H:i:s', \Drupal::time()->getRequestTime() - $interval);

  $filters = array(
    'device_sn' => "z6-33058",
    'start_date' => $start_date,
    'end_date' => $end_date,
    'output_format' => "json",
    'per_page' => 1,
    'page_num' => 1,
    'error_flag' => 'true',
    'device_depth' => 'true',
  );
  $url = $server . http_build_query($filters);
  \Drupal::logger('weather')->notice('Weather queried for: '.$start_date . ' - ' . $end_date);

  $ch = \curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Authorization: '.$token,
  ));
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_HEADER, 0);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
  curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);

  $content = curl_exec($ch);
  if (FALSE === $content) {
    print curl_error($ch);
    print curl_errno($ch);
  }
  curl_close($ch);

  if (empty($content)) {
    return;
  }
  //store results to a state variable
  \Drupal::state()->set('weather.last_results', $content);
}


